[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 1000000
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@uniswap/v3-core/=lib/v3-core/",
  "@uniswap/v2-core/=lib/v2-core/",
  "@uniswap/v2-periphery/=lib/v2-periphery/",
  "@openzeppelin-latest/=lib/openzeppelin-contracts/",
  "solmate/=lib/solmate/src/",
]
solc_version = "0.8.20"
verbosity = 1
via_ir = true

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
arbitrum = "${RPC_URL_ARBITRUM}"
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"

[etherscan]
arbitrum = {key = "${ARBISCAN_KEY}", url = "https://api.arbiscan.io/api"}
goerli = {key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api"}
mainnet = {key = "${ETHERSCAN_KEY}"}
